ALTER TABLE Employees
ADD 
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL 
        DEFAULT SYSUTCDATETIME(),
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL 
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);
GO

ALTER TABLE Employees
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.EmployeesHistory));
GO

ALTER TABLE Projects
ADD 
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL 
        DEFAULT SYSUTCDATETIME(),
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL 
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);
GO

ALTER TABLE Projects
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.ProjectsHistory));
GO

ALTER TABLE Materials
ADD 
    SysStartTime DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL 
        DEFAULT SYSUTCDATETIME(),
    SysEndTime DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL 
        DEFAULT CONVERT(DATETIME2, '9999-12-31 23:59:59.9999999'),
    PERIOD FOR SYSTEM_TIME (SysStartTime, SysEndTime);
GO

ALTER TABLE Materials
SET (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.MaterialsHistory));
GO

UPDATE Employees
SET Salary = 75000.00
WHERE EmployeeID = 2;
GO

SELECT 
    EmployeeID,
    FirstName,
    LastName,
    Salary,
    SysStartTime,
    SysEndTime
FROM Employees
FOR SYSTEM_TIME ALL
WHERE EmployeeID = 2
ORDER BY SysStartTime;
GO
